### PR TITLE
Remove account factory

### LINKED ISSUE #402: Signup: As a dev, I want the new signup controller tested.
AC:

- Test the process of signing up as a player.
- Email selection works.
- At least a single unit test in place.
- Class selection works.
- Ninja name selection works.
- More than 95% code coverage on signupController.

### PR DESCRIPTION
**Pull request by Beagle**
resolve #402

### CODE REVIEW

**Comment by tchalvak** [comment]
AC:
- (either) Automatic tests of code areas changed.
- (or) assurance that you yourself did comprehensive tests of manual behavior dealing with areas changed.

Eat your own dogfood

**Comment by tchalvak** [comment]
$request is of type object<Symfony\Component...oundation\Request>|null, but the function expects a object<NinjaWars\core\co...HttpFoundation\Request>.

On line 37 of signupController.
https://github.com/BitLucid/ninjawars/commit/7ec0919155d6187878b89825017e9bc930395bfc#diff-41774e415e6b238cbd68f858a30c2584R36

**Comment by Beagle** [comment]
No, it's just Scrutinizr picking up on the fact that we return nulls sometimes instead of throwing exceptions.

**Comment by tchalvak** [comment]
Looks good so far, testing:
Signup works
Can't sign up with existing email
Confirmation-required email domains show forms
Confirmation-required email domains try to send emails
Can log in after confirming account
...

**Comment by tchalvak** [comment]
Does not work:
http://localhost:8775/account/show_change_password_form
http://localhost:8775/account/show_change_email_form
http://localhost:8775/account/show_confirm_delete_form
Account Deletion (actually inoperabilitiization) does not work.
May be pre-existing condition.

**Comment by tchalvak** [comment]
watermelon_superhero
says "Go, do it, I'll take care of everything."

So, logged the other problems as issues, merging.

**Pull request merged**
