### PR TITLE
Remove lib accounts

### PR DESCRIPTION
**Pull request by Beagle**
Removes lib_accounts.php in favor of using the Account and Player models.

* Fixes a bug in lib_db.php when trying to bind more than one parameter-with-a-type to a query
* Attempts to resolve intermittent test failure due to the PRNG resulting in 0 gold from an NPC encounter when we don't expect it.

### CODE REVIEW

**Comment by tchalvak** [comment]
Changing account email broken:
```


Notice: Undefined variable: p_player in /srv/ninjawars/deploy/lib/control/AccountController.php on line 54

Catchable fatal error: Argument 1 passed to NinjaWars\core\data\Account::findByChar() must implement interface NinjaWars\core\data\Character, null given, called in /srv/ninjawars/deploy/lib/control/AccountController.php on line 54 and defined in /srv/ninjawars/deploy/lib/data/Account.php on line 96
```

**Comment by tchalvak** [comment]
Thanks for refactoring away lib_accounts!  I was feeling like I needed to do that soon to prevent scrutinizer from complaining about it (legitimately I guess) on every commit.

**Comment by Beagle** [comment]
pushed a fix

**Comment by tchalvak** [comment]
http://localhost:8775/#!/account

Changing email seems to still be broken, I cannot change my email on any account any more (says email is already taken on emails that should not be taken).

To reproduce: 
Signup as someone random.
Change your email to an email that could not possibly be in use, e.g. roy423452334@23421sdfjkjklasjj.com

You would expect to have your email changed, but instead you receive the error message:
"The email you provided is already in use."

I swear this was just working on master, but I'll check whether this is a pre-existing condition.

I assume there are no migrations needed for this PR.

I'm also going to create an issue for adding tests on the password change, email change, and account deletion functionality.

**Comment by tchalvak** [comment]
Damn it, it seems to be a pre-existing condition.

Prepping to merge this branch.

**Comment by tchalvak** [comment]
Merged as https://github.com/BitLucid/ninjawars/pull/663 without the npc merchant gold fix.

Closing here.

**Pull request closed without merging**
