### PR TITLE
Npc robust tests; implemented npc trait "rich"

### PR DESCRIPTION
**Pull request by tchalvak**
The initial sanity tests were naive, and were essentially just hitting the "no-npc" result because there was no player_id in the system.  This fixes that.

Additionally implemented feature trait "rich" for npcs that will have a higher minimum for the random results, mainly so that merchant can have better characteristics of a gold source.

In resources.build.php DEBUG was previously false, which made the various experimental abstract npcs still unavailable, so I changed DEBUG to true.  I guess that's appropriate for the build environment... ...maybe, hopefully?

### CODE REVIEW

**Comment by Beagle** [comment]
tests\integration\controller\NpcControllerTest::testControllerAttackAsIfAgainstAPeasant
Failed asserting that 150 is less than 150.

ninjawars/deploy/tests/integration/controller/NpcControllerTest.php:58

However, this failure didn't show up in CI. I have to imagine the random nature of the damage allowed the damage to dip to zero. @tchalvak please look into and address

**Comment by tchalvak** [comment]
Darn, yep, I failed to account for random damage being able to be zero, may have to just test for gold gain for all NPCs that reward gold, as this makes damage untestable.

**Comment by Beagle** [comment]
About to jump on this to resolve conflicts via rebase

**Comment by tchalvak** [comment]
Thanks.

**Pull request merged**
