### PR TITLE
Refactor npc player

### PR DESCRIPTION
**Pull request by Beagle**

### CODE REVIEW

**Comment by tchalvak** [comment]
Npcs seem to be broken by this, unless it's a pre-existing condition.

Create  a new character, attack a peasant, you will receive damage with no other no loss condition will occur.

Or: Create a new character, attack a peasant, attack again until you die.  Continue attacking again, your health will go negative, but you will still be able to attack.  It will start showing you the message "the peasant killed you!" or whatever, but you will be able to continue attacking.

Probably happens with a non-new character, just all that I've tested with so far.

**Comment by tchalvak** [comment]
screenshot from 2016-03-02 12 21 38

**Comment by tchalvak** [comment]
Problem not present in master branch.

**Comment by tchalvak** [comment]
There's also a subtle pre-existing condition UX problem that is in master:

- Be a level 1 new player with little strength.
- Attack a peasant2.  Receive some minor damage.
- You may or may not get any gold from the encounter (intentional).
- You may get -no- outcome message as to how the combat ended, probably because you didn't do enough damage to actually kill the peasant (intentional).
- You will get no outcome message!  (for example, "The peasant escapes!" or "You killed the peasant!" or anything, because none of those events happened and you didn't do enough damage as a level 1 to actually cause the peasant to die).

Since this is a pre-existing condition from master, I will log this one as an issue.

**Comment by Beagle** [comment]
Thanks, I will reproduce and patch.

**Comment by Beagle** [comment]
One of the things I feared came true. The queries against the DB had been written with CASE statements to prevent certain values from going negative. The refactors left that alone in most cases, but moving to using the VO instead of direct DB calls everytime led to the VO getting out of sync with the DB. At least for health, in this particular case, the issue is now resolved.

**Comment by tchalvak** [comment]
While ->death() does prevent negative hp, ->health() outputting 0 when database values < 0 is just masking the symptom of the underlying problem. Deity for example will continue to work directly from the negative health values in the database.

**Comment by tchalvak** [comment]
Ship shopped

shopped

**Pull request merged**
