### PR TITLE
Error template refactor

### PR DESCRIPTION
**Pull request by Beagle**
Simple refactor to get the juices flowing.

### CODE REVIEW

**Comment by tchalvak** [comment]
New unit tests fail.

**Comment by tchalvak** [comment]
Problem is that currently these unit tests require a database to complete, and unit tests get run before the database is instantiated.

**Comment by tchalvak** [comment]
Could move them to integration tests, or fix the database dependency if you wanted.

**Comment by Beagle** [comment]
Should be better now.

**Pull request merged**
