### PR TITLE
PROFILE: Removed, Assert: Always,

### PR DESCRIPTION
**Pull request by tchalvak**
COOKIE debug: removed.

Please note that for consistency moving forward, you'll probably want to manually remove PROFILE and DEBUG_ALL_ERRORS from your resources.php!

### CODE REVIEW

**Comment by Beagle** [comment]
Um. You also removed the deployment script in the same commit. But OK, I guess.

**Comment by tchalvak** [comment]
Unused, deprecated.

**Comment by Beagle** [comment]
It's not documented in your commit message that you removed it, that's why I mentioned it

**Comment by tchalvak** [comment]
Ok.  Well, it was intentional to remove it, I just forgot to make note of it in the commit messages.

**Pull request merged**
