### PR TITLE
Replace SESSION with Symfony sessions.

### LINKED ISSUE #290: Refactor all session code to use Symfony\Component\HttpFoundation\Session
AC:
1) deploy/lib/control/Session.class.php is removed from source tree
2) Game still runs after deleting deploy/lib/control/Session.class.php
3) `make test` still completes successfully after deleting deploy/lib/control/Session.class.php
4) Login, logout, and all other game pages run after deleting deploy/lib/control/Session.class.php
5) `grep -rq 'session_' *` returns false
6) 'grep -rq '_SESSION' *` returns false

### PR DESCRIPTION
**Pull request by Beagle**
resolve #290
Symfony sessions seem to implement a singleton pattern, except the
constructor returns a single instance of a session PER STORAGE TYPE.
This forces to use Inversion of Control principles to pass the desired
session around. Given our horrible abuse of global functions needing
access to the session, in order to support testing we need a static way
of getting the current session without relying on the conditional
singleton. nw\SessionFactory has been added to make this possible.

### CODE REVIEW

**Comment by tchalvak** [comment]
Needs more testing, as once I deleted my cookies, bad behavior ensued:

Now, when I log out, then click the login link, I'm instantly taken to a logged in state.
To replicate:
- Click logout button in ninja-menu
- From the logout page, click "Log In Again" or the "Log In" button
- You will be immediately redirected to the homepage with a logged-in ninja.

**Comment by Beagle** [comment]
Logout isn't running because the page is being cached. Ctl-shift reload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Roy R.Sent: Tuesday, December 15, 2015 09:34To: BitLucid/ninjawarsReply To: BitLucid/ninjawarsCc: BeagleSubject: Re: [ninjawars] Replace SESSION with Symfony sessions. (#323)Needs more testing, as once I deleted my cookies, bad behavior ensued:

Now, when I log out, then click the login link, I'm instantly taken to a logged in state.
To replicate:


Click logout button in ninja-menu
From the logout page, click "Log In Again" or the "Log In" button
You will be immediately redirected to the homepage with a logged-in ninja.


—Reply to this email directly or view it on GitHub.

**Comment by tchalvak** [comment]
You're right.

What is causing this to happen now?

I think that's going to cause the same problem for users.

On Tue, Dec 15, 2015 at 10:32 AM, Beagle <notifications@github.com> wrote:

> Logout isn't running because the page is being cached. Ctl-shift reload
> From: Roy R.Sent: Tuesday, December 15, 2015 09:34To:
> BitLucid/ninjawarsReply To: BitLucid/ninjawarsCc: BeagleSubject: Re:
> [ninjawars] Replace SESSION with Symfony sessions. (#323)Needs more
> testing, as once I deleted my cookies, bad behavior ensued:
>
> Now, when I log out, then click the login link, I'm instantly taken to a
> logged in state.
> To replicate:
>
>
> Click logout button in ninja-menu
> From the logout page, click "Log In Again" or the "Log In" button
> You will be immediately redirected to the homepage with a logged-in ninja.
>
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BitLucid/ninjawars/pull/323#issuecomment-164799524>.
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."

**Comment by tchalvak** [comment]
Added nocache headers to the logout page, for what that's worth...  *shrugs*

**Pull request merged**
