### PR TITLE
Nginx: Redirect index.php requests

### LINKED ISSUE #510: Index: url http://www.ninjawars.net/index.php should redirect instead of 404ing.
Whoops, though the PR was assigned to me in waffle.io, but it was just the issue instead.

### PR DESCRIPTION
**Pull request by tchalvak**
with a 302 for now, fixes #510.

### CODE REVIEW

**Comment by Beagle** [comment]
Why did you use a regex location instead of an exact match?

**Comment by tchalvak** [comment]
Cascading of priority rules prevent it from activating as an = location or a standard location, unfortunately.    Perhaps because ~ \.php gets a higher priority than location = index.php or location index.php.  Anyway, those were the first thing that I tried.

**Comment by tchalvak** [comment]
@Beagle ?  What more is needed for this PR?

**Comment by Beagle** [comment]
I want to experiment with your findings.

**Comment by Beagle** [comment]
@tchalvak  https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms  This article answers all my questions. I will be submitting a patch to this PR

**Comment by Beagle** [comment]
@tchalvak :ship:

**Pull request merged**
