### PR TITLE
Fix message display when using items on target

### LINKED ISSUE #264: Item message displayed to item user incorrectly includes message meant for victim
Current behavior when using Phosphor Powder:

> Owlet takes 46 damage.take 46 damage!
> Owlet's final health:  332 health
> Use Phosphor Powder again?

Expected behavior when using Phosphor Powder:

> Owlet takes 46 damage.
> Owlet's final health:  332 health
> Use Phosphor Powder again?

AC:
*) Expected behavior
*) Victim sees correct message

### PR DESCRIPTION
**Pull request by Beagle**
Resolve #264
Created a new concept called a "targetMessage" and use that when
generating messages to the target of an item use.

### CODE REVIEW

**Comment by tchalvak** [comment]
Giving an item to a target now sends a bad event message. Quote:

- glassbox glassbox has used a Shuriken on you at October 27, 2015, 1:50 pm and caused you to .
- glassbox You have been given a Shuriken by glassbox. 
- glassbox glassbox has used a Shuriken on you at October 27, 2015, 1:50 pm and caused you to . 
- glassbox You have been given a Shuriken by glassbox.

**Comment by tchalvak** [comment]
Ok ok, it was simpler and less painful than I thought.  I manually tested the attack capabilities of items with my manually clicking fingers, and everything worked as expected.

There is a regression with self_use items where it doesn't display any indication that the item is unusable at this time:

Displays:
[    ] (blank)
Use Kimono Again?

Instead of displaying any message that the item doesn't have an effect yet:

This item is not usable on Tchalvak, so it remains unused.

**Comment by Beagle** [comment]
so is it good?

**Comment by tchalvak** [comment]
I'm making additional fixes currently.

On Tue, Oct 27, 2015 at 11:45 PM, Beagle <notifications@github.com> wrote:

> so is it good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BitLucid/ninjawars/pull/265#issuecomment-151714269>.
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."

**Pull request merged**
