### PR TITLE
Remove unused code

### LINKED ISSUE #330: As a developer, I want to gut & simplify lib_player functions.
https://github.com/BitLucid/ninjawars/blob/5b8ba9fcf21895204b95658ce82b19f7608bd278/deploy/lib/control/lib_auth.php

self_name() is an example that deserves removal, among others.

### LINKED ISSUE #490: As a developer, I find all request handling logic for the JSON API in one location

### PR DESCRIPTION
**Pull request by Beagle**
resolve #490 
resolve #330 

This PR contains a lot, so bear with me. If you check each commit, you can see exactly what the intention was. That's going to be a lot easier than looking at all 31 files changed. Mostly, this PR deals with the fallout of removing lib_player and lib_player_list

* It moves us further away from passing IDs around and closer to passing objects around.
* It uses the ActiveRecord pattern more hopefully reducing the number of DB round trips.
* It add a make target to assist with running a single test file (somewhat janky)
* It increases code coverage of our integration tests
* It moves most API logic into an ApiController
* It introduces a helper class to write data to game-specific logs (leveling log in particular)
* Most player functions that operate on a player object are now in Player.class

The last 4 commits are minor cleanup commits but you should still review them. 

It's big, but it's a lot of important changes. Even though I haven't eliminated lib_player, I think you should merge this down after review.

### CODE REVIEW

**Comment by tchalvak** [comment]
Tested clan membership.

**Comment by tchalvak** [comment]
@beagle Attack_mod fails on some cases where change_ki would be used because the targets have more ki and are higher level than the attacker, so the attacker would gain ki.


`Fatal error: Call to undefined function change_ki() in /srv/ninjawars/deploy/www/attack_mod.php on line 324`

**Comment by Beagle** [comment]
The last commit resolves #500 and puts all of DojoController under integration test coverage

**Comment by tchalvak** [comment]
weird_ok_shaking
ship_it_but_we_regret_nothing

**Pull request merged**
