### PR TITLE
Player save fix

### PR DESCRIPTION
**Pull request by Beagle**
Fixes 3 errors in the save logic for player (1 of them for ANY save that uses the DAO)

### CODE REVIEW

**Comment by tchalvak** [comment]
Bug with skills_mod, can no longer use skills.

screenshot from 2016-02-10 16 04 15

**Comment by tchalvak** [comment]
Error with inventory_mod.


Fatal error: Class 'DatabaseConnection' not found in /srv/ninjawars/deploy/lib/control/lib_inventory.php on line 225

Please write tests for these two scripts/behaviors, if at all possible.

**Comment by tchalvak** [comment]
Notice: Undefined variable: itemsCount in /srv/ninjawars/deploy/www/skills_mod.php on line 175

**Comment by Beagle** [comment]
@tchalvak Your issues should be address now

**Comment by tchalvak** [comment]
Will test.

**Comment by tchalvak** [comment]
I ship it.
big_robot_with_ship_sword

**Comment by tchalvak** [comment]
I probably didn't test that player state gets saved after page behavior comprehensively, but that's a hard one, hopefully the automated unit tests and the additional unit test added will cover that for me.

**Pull request merged**
