### PR TITLE
Frontend state storage

### LINKED ISSUE #363: As a developer, I do not have to consider in-browser application state when working on back-end code
AC:
1) Remove all code related to the current "Settings" feature set
2) Re-implement saving front-end application state using in-browser storage

### PR DESCRIPTION
**Pull request by Beagle**
resolve #363 
Each commit in the branch should be able to tell you exactly what to test. Hopefully this can be merged in relatively quickly.

### CODE REVIEW

**Comment by tchalvak** [comment]
Casino console error upon initial (hot cache?) load:
Uncaught TypeError: Cannot read property 'appState' of undefined      casino.php: line 82

    <script>
    
    $(document).ready(function() {
        $("#bet").val(NW.storage.appState.get("bet", 1));
    
        $("#coin_flip").submit(function() {
            NW.storage.appState.set("bet", $("#bet").val());
            return true;
        });
    });
    
    </script>

**Comment by tchalvak** [comment]
Updated comment above^.

**Comment by Beagle** [comment]
Does this error go away after clearing cache or conducting a hyper-reload (shift-ctl-r)?

**Comment by tchalvak** [comment]
Fixed by adding dated version strings back on to the pertinent js/css header includes.

**Pull request merged**
