### PR TITLE
Stats unhardcoding

### PR DESCRIPTION
**Pull request by tchalvak**
Recalc stats via defines (in repo initially), allows for a lot of flexibility of progression, positive, none, negative, etc.  Deity files respond to defines, though note that for now you have to "downgrade" player health manually in the database, as if they're at 3000 health currently the system won't drop them down (but it will heal them up appropriately).

### CODE REVIEW

**Comment by Beagle** [comment]
Is this ready to go? I approve.

**Comment by tchalvak** [comment]
I'm going to add a commit to autocalculate strength/speed/stamina without using the vo, and then it'll be good to go.

**Comment by tchalvak** [comment]
I'll assign you when I do.

**Comment by tchalvak** [comment]
@beagle I guess this can be merged, I'll just rebranch.

**Pull request merged**
