### PR TITLE
Refactor inventory controller

### LINKED ISSUE #518: Item Use: Use without a target fatal errors.
AC: 
- the url http://nw.local/item/use/amanita/ should just give a user-facing error.

```
Notice: Undefined variable: targetObj in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 182

Notice: Undefined variable: targetObj in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 261

Fatal error: Uncaught exception 'InvalidArgumentException' with message '$p_target must be a Player object' in /srv/ninjawars/deploy/lib/control/AttackLegal.php:63 Stack trace: #0 /srv/ninjawars/deploy/lib/control/InventoryController.php(261): NinjaWars\core\control\AttackLegal->__construct(Object(Player), NULL, Array) #1 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->useItem() #2 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'use') #3 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /srv/ninjawars/deploy/lib/control/AttackLegal.php on line 63
```

### LINKED ISSUE #535: Inventory: targetObj not defined.
Feb 29 21:14:36 megaman error.log: 2016/02/29 21:14:08 [error] 23121#0: *548385 FastCGI sent in stderr: "PHP message: PHP Notice: Undefined variable: targetObj in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 182

### LINKED ISSUE #562: The method useItem() has an NPath complexity of 1741426490888

### PR DESCRIPTION
**Pull request by Beagle**
resolve #562 
resolve #535 
resolve #518

### CODE REVIEW

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/9

Using charcoal on self does 20 damage, apparently nothing else.

http://nw.local/item/self_use/39

Using weapons (like Bo Staff) on self does damage to self

http://nw.local/item/self_use/26

Using Katana on self does a fuckton of damage on self:

screenshot from 2016-03-12 13 21 00

**Comment by tchalvak** [comment]
When you're dead, you can still use items on yourself, and... ?suicide more?

**Comment by tchalvak** [comment]
Item use no longer respects being dead in any way shape or form.  Needs some tests to go RED on this matter.

screenshot from 2016-03-12 13 22 28

**Comment by tchalvak** [comment]
This
screenshot from 2016-03-12 13 24 42

**Comment by tchalvak** [comment]
Can use a smoke bomb on self when dead.

screenshot from 2016-03-12 14 00 20

**Comment by Beagle** [comment]
Using AttackLegal now for self_use. Will test a few of your cases. If you test and it's successful, please merge.

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/4/128274/?link_back=inventory


Notice: Undefined variable: target in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 142

Fatal error: Uncaught exception 'InvalidArgumentException' with message '$p_target must be a Player object' in /srv/ninjawars/deploy/lib/control/AttackLegal.php:61 Stack trace: #0 /srv/ninjawars/deploy/lib/control/InventoryController.php(142): NinjaWars\core\control\AttackLegal->__construct(Object(Player), NULL, Array) #1 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->selfUse() #2 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'self_use') #3 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /srv/ninjawars/deploy/lib/control/AttackLegal.php on line 61

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/26


Notice: Undefined variable: target in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 142

Fatal error: Uncaught exception 'InvalidArgumentException' with message '$p_target must be a Player object' in /srv/ninjawars/deploy/lib/control/AttackLegal.php:61 Stack trace: #0 /srv/ninjawars/deploy/lib/control/InventoryController.php(142): NinjaWars\core\control\AttackLegal->__construct(Object(Player), NULL, Array) #1 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->selfUse() #2 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'self_use') #3 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /srv/ninjawars/deploy/lib/control/AttackLegal.php on line 61

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/3


Notice: Undefined variable: target in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 142

Fatal error: Uncaught exception 'InvalidArgumentException' with message '$p_target must be a Player object' in /srv/ninjawars/deploy/lib/control/AttackLegal.php:61 Stack trace: #0 /srv/ninjawars/deploy/lib/control/InventoryController.php(142): NinjaWars\core\control\AttackLegal->__construct(Object(Player), NULL, Array) #1 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->selfUse() #2 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'self_use') #3 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /srv/ninjawars/deploy/lib/control/AttackLegal.php on line 61

**Comment by Beagle** [comment]
Resolved in latest push

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/39


Tchalvak takes 170 damage.
You take 170 damage!
Tchalvak's final health:   480 health
Use Bo Staff again?

**Comment by tchalvak** [comment]
http://nw.local/item/self_use/23

Kimonos before: 19

Tchalvak's final health:   330 health
Use Kimono again?  

Kimonos after: 18

**Comment by Beagle** [comment]
@tchalvak Do kimono and bo staff have self_use set to true in your database?

**Comment by tchalvak** [comment]
I expect so.

Still, needs either a migration for the data, or a guard statement, or a reclassification.

Kimono usage on live, for example:

http://www.ninjawars.net/item/self_use/23

**Comment by tchalvak** [comment]
image

**Comment by Beagle** [comment]
We can't put a guard statement for something that cannot be
interrogated. I'm not going to write a guard statement for everything
that claims to be self_usable but somehow isn't. Fix the data.

**Comment by Beagle** [comment]
bump
I'm waiting on this before I push the change to the Player namespace.

**Comment by tchalvak** [comment]
It needs a migration at a minimum.  *shrugs*  Had an existing prevention
mechanism, mechanism no longer holds, so I'll get to making a data
modification when I feel ambitious enough to parse the conditions that the
original prevention mechanism used.

On Mon, Mar 14, 2016 at 10:08 PM, Beagle <notifications@github.com> wrote:

> bump
> I'm waiting on this before I push the change to the Player namespace.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BitLucid/ninjawars/pull/563#issuecomment-196616221
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."

**Pull request merged**
