### PR TITLE
Remove /core/ symlink

### PR DESCRIPTION
**Pull request by Beagle**
@tchalvak This removes the core symlink and uses the autoloader instead. Please consider this for merging.

### CODE REVIEW

**Comment by tchalvak** [comment]
But lib is a misnomer.  Core is the appropriate name.

**Comment by tchalvak** [comment]
I simply have not wanted to git mv /lib/ /core/ on 90% of the codebase, moving history in so much of the codebase for a naming issue.

**Comment by Beagle** [comment]
Either rename it or drop the symlink. Symlinks committed to the
repository are NOT the answer. It creates confusion for zero value. The
naming value can be achieved via an alias in autoloading which is far
more appropriate for your use case.

**Comment by tchalvak** [comment]
Mmmm

**Pull request merged**
