### PR TITLE
Skills_mod controllerified.

### PR DESCRIPTION
**Pull request by tchalvak**
Urls like: http://nw.local/skill/use/Fire%20Bolt/tchalvak And http://nw.local/skill/self_use/Heal now work.

Player::findByName($name) now exists.

### CODE REVIEW

**Comment by tchalvak** [comment]
@Beagle thoughts?

**Comment by Beagle** [comment]
@tchalvak Self-use of a skill shows a button for "use again" with the wrong URL (use instead of self_use). It's possible that using a slug to differentiate use and self_use is the wrong strategy and instead we should add the target as a slug at the end. I feel that we shouldn't merge this down until self-use of unstealth doesn't throw an invalid target error on re-use

**Comment by tchalvak** [comment]
@beagle good to go

**Comment by tchalvak** [comment]
@beagle merge plz

**Pull request merged**
